### ISSUE TITLE
AArch64 semantics built with amd64 target triple

### ISSUE THREAD

**Issue by artemdinaburg** [trailofbits/remill#116]
The BCCompiler CMake build system does not (yet :) ) support setting a target triple for emitting bitcode. Therefore, everything is built as native arch triples (very likely amd64). For AArch64 semantics, we obviously want to emit bitcode with the AArch64 triple of correct endianness.

It should be a matter of modifying the build system to support a `${BC_COMPILER_TRIPLE}` flag and setting it in each semantics generation CMakeList.txt

**Comment by pgoodman** [comment]
I thought that I got closer to getting this right. I have added in a new `ARCH <target_arch>` thing into the `add_runtime`. I don't think it's actually sending the right params through though.

**Comment by pgoodman** [comment]
I am thinking of going back on this. Specifically, I envision use cases where the bitcode needs to be compilable for the host arch, but bot necessarily the target arch.

**Comment by pgoodman** [comment]
Closing this. Compiling semantics to a specific arch happens to be a bit trickier than intended. Specifically, `-target` needs to be manually specified, and then include search paths go all wonky. Also, there doesn't happen to be a `gcc-multilib` package on Scaleway's aarch64 ubuntu 16.04 vms, so that doesn't help things in that department. Finally, I've observed that really we probably want to be compiling all bitcode using the `x86_64-unknown-unknown` triple. The following illustrates some annoying ABI things:

```c
struct P {
   int *y;
};

int foo(struct P x) {
   return *(x.y);
}
```

for amd64, this compiles down into:

```lllvm
define i32 @foo(P)(i32* nocapture readonly) local_unnamed_addr #0 {
%2 = load i32, i32* %0, align 4, !tbaa !2
ret i32 %2
}
```

for aarch64, this compiles down into:

```llvm
define i32 @foo(i64) local_unnamed_addr #0 {
 %2 = inttoptr i64 %0 to i32*
 %3 = load i32, i32* %2, align 4, !tbaa !1
 ret i32 %3
}
```
